version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.letsencrypt.acme.email=${LE_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      # (Optional, while debugging to avoid LE rate limits)
      # - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Bind mount so you can chmod 600 without sudo inside container volumes
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [web]
    restart: unless-stopped

  web:
    image: nginx:alpine
    volumes:
      - ./web:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`com-cloud.cloud`) && PathPrefix(`/`)
      - traefik.http.routers.web.entrypoints=websecure
      - traefik.http.routers.web.tls.certresolver=letsencrypt
      - traefik.http.routers.web.priority=1
      - traefik.http.services.web.loadbalancer.server.port=80
    networks: [web]
    restart: unless-stopped

  assistant:
    image: sithuyehtun/full_duplex_assistant:${IMAGE_TAG:-latest}
    env_file:
      - ./src/assistant/.env
    environment:
      - ENABLE_VOICE=0
      - ALLOWED_ORIGINS=https://com-cloud.cloud
    expose:
      - "8000"
    labels:
      - traefik.enable=true

      # ===== WebSocket route =====
      - traefik.http.routers.ws.rule=Host(`com-cloud.cloud`) && PathPrefix(`/ws`)
      - traefik.http.routers.ws.entrypoints=websecure
      - traefik.http.routers.ws.tls.certresolver=letsencrypt
      - traefik.http.routers.ws.priority=100
      - traefik.http.routers.ws.middlewares=ws-headers
      - traefik.http.services.ws.loadbalancer.server.port=8000

      # Explicit WS upgrade headers (extra-safe)
      - traefik.http.middlewares.ws-headers.headers.customrequestheaders.Upgrade=websocket
      - traefik.http.middlewares.ws-headers.headers.customrequestheaders.Connection=Upgrade

      # ===== REST route =====
      - traefik.http.routers.api.rule=Host(`com-cloud.cloud`) && PathPrefix(`/api`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=letsencrypt
      - traefik.http.routers.api.priority=50
      - traefik.http.services.api.loadbalancer.server.port=8000
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks: [web]
    restart: unless-stopped

networks:
  web:
    driver: bridge
