assistant:
  build:
    context: ./src                # build context contains your /assistant code
    dockerfile: ./assistant/utils/Dockerfile
  image: full-duplex-assistant:latest
  # WORKDIR is /app from your Dockerfile; PYTHONPATH=/app/src is already set there
  env_file:
    - ./src/assistant/.env        # must contain OPENAI_API_KEY=...
  environment:
    - ENABLE_VOICE=0
    - ALLOWED_ORIGINS=https://com-cloud.cloud
  expose:
    - "8000"
  healthcheck:
    test: ["CMD-SHELL", "python -c \"import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://127.0.0.1:8000/healthz', timeout=3).status==200 else sys.exit(1)\""]
    interval: 10s
    timeout: 5s
    retries: 6
    start_period: 20s
  labels:
    - "traefik.enable=true"
    - "traefik.docker.network=full_duplex_web"
    - "traefik.http.routers.assistant.rule=Host(`com-cloud.cloud`) && PathPrefix(`/api`)"
    - "traefik.http.routers.assistant.entrypoints=websecure"
    - "traefik.http.routers.assistant.tls.certresolver=letsencrypt"
    - "traefik.http.routers.assistant.priority=100"
    - "traefik.http.services.assistant.loadbalancer.server.port=8000"
  networks: [web]
  restart: unless-stopped
